# golangci-lint configuration
# Based on Google Go Style Guide recommendations

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional recommended linters
    - gofmt
    - goimports
    - gocritic
    - revive
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - copyloopvar
    - nolintlint

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/alp/suumo-hunter-go

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocritic
        - unparam

    # Exclude doc.go files from package-comments check
    - path: doc\.go
      linters:
        - revive

  max-issues-per-linter: 50
  max-same-issues: 10
